"""Compliance event taxonomy."""

from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    CONTROL_DECISION = "CONTROL_DECISION"
    RISK_EVALUATION = "RISK_EVALUATION"
    PRE_TRADE_VALIDATION = "PRE_TRADE_VALIDATION"
    ORDER_PLACED = "ORDER_PLACED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_EXITED = "ORDER_EXITED"
    PORTFOLIO_UPDATE = "PORTFOLIO_UPDATE"
    AUTONOMOUS_TICK = "AUTONOMOUS_TICK"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    RECONCILIATION_RUN = "RECONCILIATION_RUN"
    STRATEGY_GOVERNANCE_DECISION = "STRATEGY_GOVERNANCE_DECISION"
    STRATEGY_PERFORMANCE_UPDATE = "STRATEGY_PERFORMANCE_UPDATE"
    ICB_DECISION = "ICB_DECISION"
    ICB_FAILURE = "ICB_FAILURE"
    CHAOS_SCENARIO_STARTED = "CHAOS_SCENARIO_STARTED"
    FAULT_INJECTED = "FAULT_INJECTED"
    SYSTEM_RESPONSE = "SYSTEM_RESPONSE"
    RISK_DECISION = "RISK_DECISION"
    EXECUTION_OUTCOME = "EXECUTION_OUTCOME"
    RECONCILIATION_RESULT = "RECONCILIATION_RESULT"
    CHAOS_SCENARIO_COMPLETED = "CHAOS_SCENARIO_COMPLETED"
